### ISSUE TITLE
Show IDs in expander graph of hierachy visualisation

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/network#10]
To facilitate the work of our Fachteam to remove unwanted categories in the hierachy, please display also the WikiData Ids in the expander graph of https://github.com/icebreaker-science/network/issues/2.
They will then note all the ids of unwanted categories up to a depth of 3-4 so that we can remove them from our database.

**Comment by chaoran-chen** [comment]
Isn't it already done by @dajenet?

https://dev.icebreaker.science/www/hierarchy_collabsible.html
